[package]
name = "wasmsign"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"

[dependencies]
byteorder = "*"
clap = "*"
ed25519-dalek = "*"
failure = "*"
parity-wasm = "*"
rand = "*"
sha2 = "*"