[package]
name = "wasmsign"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]

[dependencies]
byteorder = "1"
clap = "2"
ed25519-dalek = "0.8"
failure = "0.1"
parity-wasm = "0.34"
rand = "0.5"
sha2 = "0.7"
