[package]
name = "wasmsign"
version = "0.1.0"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"

[dependencies]
byteorder = "1"
clap = "2"
ed25519-dalek = "0.9"
failure = "0.1"
parity-wasm = "0.35"
rand = "0.6"
sha2 = "0.8"
